const input=document.getElementById('inputText'),output=document.getElementById('resultArea'),resultHint=document.getElementById('resultHint'),resultMeta=document.getElementById('resultMeta'),charCount=document.getElementById('charCount'),wordCount=document.getElementById('wordCount'),copyBtn=document.getElementById('copyBtn'),copyAllBtn=document.getElementById('copyAllBtn'),clearBtn=document.getElementById('clearBtn'),sampleBtn=document.getElementById('sampleBtn'),subjectText=document.getElementById('subjectText'),emailFields=document.getElementById('emailFields'),modeHint=document.getElementById('modeHint'),toneDescription=document.getElementById('toneDescription'),statusText=document.getElementById('statusText'),modeStats=document.getElementById('modeStats'),useBtn=document.getElementById('useBtn'),restoreBtn=document.getElementById('restoreBtn');
let lastResult='',mode='email',tone='professional',previousDraft='',previousSubject='',lastChanges=[];
const samples={email:{subject:'Firewall logs — requested timeframe',body:'Hi Team,\n\nPlease find attached the report. Kindly check it and revert back to me if there is any issue. We need the customer to confirm the exact timeframe.\n\nThanks & Regards,\nAditya'},conversation:{subject:'',body:'hi, can you please check this once and let me know if there is any issue. i need this asap'}};
function words(t){return t.trim()?t.trim().split(/\s+/).length:0}
function showEmpty(message='Your polished text will appear here.',hint='Choose an action below to get started.'){output.innerHTML=`<div class="empty-state"><div class="spark">✦</div><p>${message}</p><span>${hint}</span></div>`;resultHint.textContent='Ready when you are';resultMeta.textContent='';copyBtn.disabled=true;useBtn.disabled=true;copyAllBtn.classList.add('hidden');restoreBtn.classList.add('hidden');lastResult='';lastChanges=[]}
function updateCounts(){charCount.textContent=`${input.value.length} / 5000`;wordCount.textContent=`${words(input.value)} words`}
function renderMeta(action){const n=lastChanges.length;resultMeta.textContent=`${words(lastResult)} words · ${lastResult.length} characters${n?` · ${n} correction${n===1?'':'s'} applied`:''}`}
function applyAction(action){const source=input.value.trim();if(!source){showEmpty('Add some text first.','Paste an email or conversation, then choose an action.');return}previousDraft=input.value;previousSubject=subjectText.value;let result;if(action==='grammar')result=clearwriteCore(source);else if(action==='professional')result={text:clearwriteImprove(source),changes:clearwriteCore(source).changes};else if(action==='concise')result={text:clearwriteConcise(source),changes:clearwriteCore(source).changes};else result={text:clearwriteTone(source,tone),changes:clearwriteCore(source).changes};lastResult=result.text;lastChanges=result.changes;output.textContent=lastResult;resultHint.textContent=action==='concise'?'Shortened version ready.':action==='tone'?`${tone[0].toUpperCase()+tone.slice(1)} tone applied.`:`${action==='grammar'?'Grammar':'Writing'} pass complete.`;renderMeta(action);copyBtn.disabled=false;useBtn.disabled=false;restoreBtn.classList.remove('hidden');if(mode==='email'&&subjectText.value.trim())copyAllBtn.classList.remove('hidden');statusText.textContent=navigator.onLine?'V5 writing engine · running locally':'V5 writing engine · offline';}
input.addEventListener('input',()=>{updateCounts();if(!input.value.trim())showEmpty()});
subjectText.addEventListener('input',()=>{if(lastResult&&subjectText.value.trim())copyAllBtn.classList.remove('hidden')});
document.querySelectorAll('.action').forEach(b=>b.addEventListener('click',()=>applyAction(b.dataset.action)));
document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.mode').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});b.classList.add('active');b.setAttribute('aria-selected','true');mode=b.dataset.mode;emailFields.classList.toggle('hidden',mode!=='email');modeHint.textContent=mode==='email'?'Subject, greeting, body and sign-off.':'Slack, Teams, or chat-style message.';modeStats.textContent=mode==='email'?'Email mode':'Conversation mode';input.placeholder=mode==='email'?'Start writing or paste your message here...':'Start writing or paste your conversation here...';if(!input.value.trim())showEmpty()}));
document.querySelectorAll('.tone').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tone').forEach(x=>x.classList.remove('active'));b.classList.add('active');tone=b.dataset.tone;const d={professional:'Balanced workplace writing',formal:'Polished and respectful',friendly:'Warm and approachable',assertive:'Clear and confident'};toneDescription.textContent=d[tone]}));
sampleBtn.addEventListener('click',()=>{input.value=samples[mode].body;subjectText.value=samples[mode].subject;updateCounts();showEmpty('Example loaded.','Choose an action below to improve it.')});
clearBtn.addEventListener('click',()=>{input.value='';subjectText.value='';updateCounts();showEmpty();input.focus()});
useBtn.addEventListener('click',()=>{if(!lastResult)return;previousDraft=input.value;previousSubject=subjectText.value;input.value=lastResult;updateCounts();useBtn.disabled=true;restoreBtn.classList.remove('hidden');statusText.textContent='Improved version moved into your draft';resultHint.textContent='Applied to draft'});
restoreBtn.addEventListener('click',()=>{if(previousDraft==='')return;const current=input.value;input.value=previousDraft;subjectText.value=previousSubject;previousDraft=current;updateCounts();statusText.textContent='Previous draft restored';resultHint.textContent='Draft restored'});
copyBtn.addEventListener('click',async()=>{if(!lastResult)return;try{await navigator.clipboard.writeText(lastResult);const p=copyBtn.textContent;copyBtn.textContent='Copied';setTimeout(()=>copyBtn.textContent=p,1200)}catch{resultMeta.textContent='Copy unavailable — select the text manually.'}});
copyAllBtn.addEventListener('click',async()=>{if(!lastResult)return;const full=`Subject: ${subjectText.value.trim()}\n\n${lastResult}`;try{await navigator.clipboard.writeText(full);copyAllBtn.textContent='Copied';setTimeout(()=>copyAllBtn.textContent='Copy with subject',1200)}catch{resultMeta.textContent='Copy unavailable — select the text manually.'}});
updateCounts();